- hosts: all
  tasks:
  - name: Reboot prior updates
    win_reboot:
      pre_reboot_delay: 60
      reboot_timeout: 3600
      
  - name: Install all updates
    win_updates:
      category_names:
      - CriticalUpdates
      - DefinitionUpdates
      - SecurityUpdates
      - Updates
      - ServicePacks
      - FeaturePacks
      - UpdateRollups
      log_path: C:\Temp\Updates.log
      server_selection: windows_update
      reboot: yes
      reboot_timeout: 3600
