- hosts: all
  tasks:
  - name: Install all updates and reboot if necessary
    win_updates:
      category_names: all
      server_selection: windows_update
      reboot: yes 
    register: result
    
  - debug: var=result.updates.title
