- hosts: all
  tasks:
  - name: Install all updates and reboot if necessary
    win_updates:
      server_selection: windows_update
      reboot: yes
    
  # - debug: updates.title
  - name: Reboot host
    win_reboot:
      pre_reboot_delay: 60
      reboot_timeout: 600
