- hosts: all
  tasks:
  - name: Install all updates and reboot if necessary
    win_updates:
      reboot: yes
      category_names:
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
        - ServicePacks
        - FeaturePacks
        - UpdateRollups
      log_path: C:\Temp\Updates.log
      server_selection: windows_update

    
  # - debug: updates.title
  - name: Reboot host
    win_reboot:
      pre_reboot_delay: 60
      reboot_timeout: 600
