- hosts: all
  tasks:
    - name: Get host's name
      win_shell: Write-Host $env:computername
      register: stdout

    - debug: var={{ stdout.stdout_lines }}
    - debut: var={{ stdout.stderr_lines }}
